Repository digital-peaks/web-aoa-frontend, pull requests merged in 2021-12, with the labels that each got.

#21 add job overview
  package-lock.json
  package.json
  src/App.vue
  src/common/api.js
  src/common/config.js
  src/components/TimeAgo.vue
  src/features/input/InputView.vue
  src/features/jobs/JobsList.vue
  src/features/jobs/JobsView.vue
  src/store/index.js
Labels: enhancement, frontend

#22 Output view
  src/assets/download_icon.png
  src/components/DownloadIcon.vue
  src/features/input/InputView2.vue
  src/features/output/OutputView.vue
Labels: help wanted, frontend, task

#25 add basic job input
  src/App.vue
  src/common/api.js
  src/features/input/InputView.vue
  src/features/output/OutputView.vue
Labels: enhancement, frontend

#28 Add vuetify
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/main.js
  src/plugins/vuetify.js
  vue.config.js
Labels: enhancement

#29 use Vuetify components for job input form
  package-lock.json
  src/features/input/InputView.vue
Labels: enhancement, frontend

#32 visualize new job status
  src/features/jobs/JobsView.vue
Labels: enhancement

#30 add job form validation
  package-lock.json
  package.json
  src/App.vue
  src/features/input/InputView.vue
Labels: enhancement

#36 enhance job overview
  src/App.vue
  src/components/TimeAgo.vue
  src/features/input/InputView.vue
  src/features/jobs/JobsView.vue
  src/router/index.js
Labels: enhancement

#35 add ability to use existing model
  src/common/api.js
  src/features/input/InputView.vue
Labels: enhancement

#38 Some changes in layer and icon
  src/assets/markerIconBlue.png
  src/assets/markerIconBlueBorder.png
  src/assets/markerIconGreen.png
  src/assets/markerIconGreen.svg
  src/assets/markerIconPink.png
  src/assets/markerIconRedCross.png
  src/assets/markerIconRedCrossWithBlack.png
  src/assets/markerIconRedCrossWithBlackEvenThicker.png
  src/assets/markerIconRedCrossWithBlackThick.png
  src/assets/markerIconRose.png
  src/assets/markerIconYellow.png
  src/components/ColorLegend.vue
  src/features/output/OutputView.vue
  src/main.js
Labels: frontend

#39 add job name on output
  src/features/output/OutputView.vue
Labels: enhancement

#46 Output tooltips
  src/features/output/OutputView.vue
Labels: enhancement, frontend

#49 Load data from api for specific job
  src/common/api.js
  src/features/output/OutputView.vue
  src/store/index.js
Labels: enhancement, frontend

#48 Input tooltips
  src/features/input/InputView.vue
Labels: enhancement, good first issue, frontend
