Repository digital-peaks/web-aoa-frontend, pull requests merged in 2022-01, with the labels that each got.

#50 layer not available -> disable row in output
  src/features/output/OutputView.vue
Labels: enhancement, good first issue, frontend

#52 Add mla to input site
  src/features/input/InputView.vue
Labels: enhancement, help wanted, frontend

#62 enhance configuration for env variables
  Dockerfile.production
  README.md
  ops/nginx.entrypoint.sh
  public/index.html
  src/common/config.js
Labels: documentation, enhancement, frontend

#64 fix nginx config
  Dockerfile.production
  ops/nginx.default.conf
Labels: bug, frontend

#63 add login and session handling
  src/App.vue
  src/common/api.js
  src/features/jobs/JobsView.vue
  src/features/login/LoginView.vue
  src/router/index.js
  src/store/index.js
Labels: enhancement, frontend

#84 Download Job Parameters
  src/features/output/OutputView.vue
Labels: enhancement, frontend

#101 add mobile navigation
  src/App.vue
Labels: enhancement, frontend
